/**
 * Export-related type definitions for MarkRead
 * Defines interfaces for PDF export operations, progress tracking, and error handling
 */

import type { DefaultFileEntry } from './entities';

export type ExportJobType = 'single-pdf' | 'folder-pdf';
export type ExportJobStatus = 'pending' | 'in-progress' | 'completed' | 'failed' | 'cancelled';
export type PageSize = 'A4' | 'Letter';

export interface ExportJob {
  id: string;
  type: ExportJobType;
  status: ExportJobStatus;
  source: string;
  destination: string;
  options: ExportOptions;
  progress: ExportProgress;
  createdAt: Date;
  startedAt?: Date;
  completedAt?: Date;
  error?: ExportError;
}

export interface ExportOptions {
  pageSize: PageSize;
  margins: { top: number; bottom: number; left: number; right: number };
  printBackground: boolean;
  includeSubfolders?: boolean;
  generateTOC?: boolean;
}

export interface ExportProgress {
  currentFile?: string;
  filesProcessed: number;
  totalFiles: number;
  percentComplete: number;
}

export interface ExportError {
  code: string;
  message: string;
  details?: string;
  retryable: boolean;
}

export interface FolderExportOptions extends ExportOptions {
  includeSubfolders: boolean;
  generateTOC: boolean;
  coverPage?: {
    title: string;
    subtitle?: string;
    author?: string;
  };
  /** Git repository and branch info for the cover page */
  gitInfo?: {
    repoName?: string;
    repoUrl?: string;
    branch?: string;
  };
  /** When exporting a subfolder, this is the path relative to the root */
  subfolderPath?: string;
  /** PDF styling and layout options */
  pdfStyling?: PdfStylingOptions;
  /** Default files configuration for priority ordering in export */
  defaultFilesToOpen?: DefaultFileEntry[];
}

/** PDF styling and layout configuration */
export interface PdfStylingOptions {
  /** Cover page options */
  coverPage: {
    /** Show the MarkRead logo on cover page */
    showLogo: boolean;
    /** Show branding block at bottom (MarkRead version + schalken.net) */
    showBranding: boolean;
  };
  /** Header options */
  header: {
    /** Enable page header */
    enabled: boolean;
    /** Show folder/repo info in header */
    showFolderInfo: boolean;
    /** Show relative path of current document */
    showRelativePath: boolean;
    /** Custom header text (overrides automatic content) */
    customText?: string;
  };
  /** Footer options */
  footer: {
    /** Enable page footer */
    enabled: boolean;
    /** Show page numbers */
    showPageNumbers: boolean;
    /** Show "Generated by MarkRead" text */
    showBranding: boolean;
    /** Custom footer text */
    customText?: string;
  };
  /** Table of contents options */
  toc: {
    /** Show page numbers in TOC */
    showPageNumbers: boolean;
  };
  /** Section separator options */
  sectionSeparators: {
    /** Show page numbers on separator pages */
    showPageNumbers: boolean;
  };
}

export interface MarkdownFile {
  path: string;
  relativePath: string;
  title: string;
  content: string;
  renderedHtml?: string;
  order: number;
}

export interface CoverPage {
  title: string;
  subtitle?: string;
  date: Date;
  author?: string;
  logo?: string;
}

export interface TOCEntry {
  title: string;
  level: number;
  pageNumber?: number;
  anchor: string;
  children: TOCEntry[];
}

export interface ExportSettings {
  defaultPageSize: PageSize;
  defaultMargins: { top: number; bottom: number; left: number; right: number };
  printBackground: boolean;
  defaultOutputDirectory?: string;
  includeSubfoldersDefault: boolean;
  recentExports: RecentExport[];
  /** Default PDF styling options */
  pdfStyling: PdfStylingOptions;
}

/** Default PDF styling options */
export const DEFAULT_PDF_STYLING: PdfStylingOptions = {
  coverPage: {
    showLogo: true,
    showBranding: true,
  },
  header: {
    enabled: true,
    showFolderInfo: true,
    showRelativePath: true,
  },
  footer: {
    enabled: true,
    showPageNumbers: true,
    showBranding: false,
  },
  toc: {
    showPageNumbers: true,
  },
  sectionSeparators: {
    showPageNumbers: true,
  },
};

export interface RecentExport {
  source: string;
  destination: string;
  timestamp: Date;
  type: ExportJobType;
}

export interface ExportLogEntry {
  timestamp: Date;
  jobId: string;
  type: ExportJobType;
  source: string;
  destination: string;
  status: 'completed' | 'failed' | 'cancelled';
  duration: number;
  filesProcessed: number;
  error?: {
    code: string;
    message: string;
  };
}

export enum ExportErrorCode {
  PERMISSION_DENIED = 'EXPORT_PERMISSION_DENIED',
  FILE_NOT_FOUND = 'EXPORT_FILE_NOT_FOUND',
  DISK_FULL = 'EXPORT_DISK_FULL',
  MEMORY_EXCEEDED = 'EXPORT_MEMORY_EXCEEDED',
  RENDER_FAILED = 'EXPORT_RENDER_FAILED',
  INVALID_OPTIONS = 'EXPORT_INVALID_OPTIONS',
  CANCELLED = 'EXPORT_CANCELLED',
  TIMEOUT = 'EXPORT_TIMEOUT',
  RATE_LIMITED = 'EXPORT_RATE_LIMITED',
  NO_FILES = 'EXPORT_NO_FILES',
  NOT_FOUND = 'EXPORT_NOT_FOUND',
  ALREADY_COMPLETED = 'EXPORT_ALREADY_COMPLETED',
  UNKNOWN = 'EXPORT_UNKNOWN'
}
